apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels-service
  template:
    metadata:
      labels:
        app: hotels-service
    spec:
      containers:
        - name: hotels-service
          image: hotels-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              value: "4001"
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
            - name: MINIO_BUCKET
              value: "hotels"
            - name: MONGODB_URI
              value: "mongodb://admin:admin@mongodb:27017/sta?authSource=admin"
            - name: MONGODB_DB
              value: "sta"