apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: smart-travel-agency
  labels:
    app: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6
          ports:
            - containerPort: 27017
              name: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin"
            - name: MONGO_INITDB_DATABASE
              value: "sta"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: mongo-data
          hostPath:
            path: /mnt/sta-mongo
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: smart-travel-agency
  labels:
    app: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-seed-js
  namespace: smart-travel-agency
data:
  init.js: |
    db = db.getSiblingDB("sta");
    db.users.insertMany([
      { _id: "u1", name: "Alice", email: "alice@example.com" },
      { _id: "u2", name: "Bob", email: "bob@example.com" }
    ]);
    db.flights.insertMany([
      { _id: "f1", from: "TLV", to: "JFK", date: "2025-07-10" },
      { _id: "f2", from: "JFK", to: "TLV", date: "2025-07-20" }
    ]);
    db.hotels.insertMany([
      { _id: "h1", name: "Hotel Tel Aviv", city: "Tel Aviv" },
      { _id: "h2", name: "Hotel New York", city: "New York" }
    ]);
    db.bookings.insertOne({
      _id: "b1",
      userId: "u1",
      flightId: "f1",
      hotelId: "h2",
      status: "confirmed"
    });
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-seed
  namespace: smart-travel-agency
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-seed
          image: mongo:6
          command: ["mongo", "mongodb://staadmin:staadminpw@mongodb:27017/sta", "/seed/init.js"]
          volumeMounts:
            - name: seed-js
              mountPath: /seed
      volumes:
        - name: seed-js
          configMap:
            name: mongo-seed-js