apiVersion: v1
kind: Service
metadata:
  name: sta-auth-service
  namespace: smart-travel-agency
  labels:
    app: sta-auth-service
spec:
  type: ClusterIP
  selector:
    app: sta-auth-service
  ports:
    - protocol: TCP
      port: 4003
      targetPort: 4003