apiVersion: v1
kind: Service
metadata:
  name: sta-flights-service
  namespace: smart-travel-agency
  labels:
    app: sta-flights-service
spec:
  type: ClusterIP
  selector:
    app: sta-flights-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002