apiVersion: v1
kind: Service
metadata:
  name: weather
  labels:
    app: weather
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP